### ISSUE TITLE
[messbox] not working with commas

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1034]
as discussed in https://github.com/porres/pd-else/pull/1032

@sebshader , what is your system's configuration?

**Comment by sebshader** [comment]
@porres I'm using osx 10.14.6 mojave, mainly testing using the pd-next version 0.51-4 with tk 8.6.10
I also tested with 0.51-4 vanilla and it works fine there too though.

**Comment by sebshader** [comment]
@porres ok, I have some idea of what's going on here.
[messbox] starts a timer when a "bang" is sent to it, that gives tcl/tk 5 milliseconds to send "anything" messages to [messbox]. If "anything" messages are received after that time, they are ignored. However, this is not true of "output" messages, which the 1st message in the list sent from tcl will be.

the reason for this is to differentiate between messages coming back from tcl and messages sent to an inlet. If it were not there then "anything" messages would be sent out the outlet when received at the inlet.

one solution might be to split the messages with commas on the tcl side so that each message can be sent as an "output" message

another solution might be to set up a proxy class that can't be accessed by the inlets but can have messages sent to a bound symbol.

**Comment by porres** [comment]
damn, it's the same as mine!!! 0.51-4 on mojave 10.14.6, so weird that it stopped working for me at one point up to the last release (beta 39) and still works for you!

**Comment by sebshader** [comment]
@porres I might be able to fix it with a proxy class. should I just add to the bugfix branch or start a new branch/pr?

**Comment by porres** [comment]
do it as you wish ;) i dont care

**Comment by porres** [comment]
I can confirm it works, THANKS! https://github.com/porres/pd-else/pull/1035
