### ISSUE TITLE
pvoc.player~ only outputs crackles

### ISSUE THREAD

**Issue by boonier** [porres/pd-else#1158]
Affects example from the help file, and also when in my patch.

Pd 0.52.1
ELSE v1.0.0_beta45
macOS 12.0.1 / M1 silicon

Any other details you need?

cheers

**Comment by porres** [comment]
Hi, made some revisions and fixed a couple of issues with this object => see https://github.com/porres/pd-else/commit/496f9632018242a7e6f8b4aefa46e8c15435e41f

but I guess your problem is just that this is a cpu heavy abstraction and you need to increase the audio latency in your settings.

I guess I wasn't having this issue with my computer because it was a last gen macbook pro, but I'm now using a quite old macbook air and was getting crackles with my latency down to pd's default of 5ms, so I increased it to 20ms and it seems to work fine now.

**Comment by boonier** [comment]
Cool thanks, I'll check it out. I was having this issue on a new M1 Max as it happens! But I will play with the latency settings. Cheers

**Comment by boonier** [comment]
oh btw is this in a new beta release or a few files to drop in?

**Comment by porres** [comment]
this what? my latest fix? it's here on the 'head', and it's an abstraction, so you can just download it

**Comment by porres** [comment]
hmmm M1 macs should be able to handle this and perform well
