### ISSUE TITLE
camomile: store and rec don't work

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1174]
@timothyschoen can you help me get to the bottom of this?

**Comment by porres** [comment]
ping @timothyschoen

**Comment by timothyschoen** [comment]
Yes, I'm aware! I don't know what's going on yet, I still have to look into it. 

Current state for PlugData is that the GUI is almost complete feature-wise, so I'm trying to fix the last things so I'll just be done with that (at least until v1.0). This will probably take 2 weeks. It would be nice to finish this because it's the most time-consuming part and also the part that's most prone to bugs.

After that my focus is going to be completely on fixing bugs, documentation and making sure ELSE, cyclone and vanilla objects and features completely work. This will be the first thing on my list!

**Comment by timothyschoen** [comment]
I'm very busy with finishing school right now so this got pushed back a little bit... I'll get to it though!

**Comment by porres** [comment]
this was fixed @timothyschoen, right?

**Comment by timothyschoen** [comment]
Not really, it just randomly started working in plugdata, not sure if that's also the case in camomile

**Comment by porres** [comment]
camomile is dead :(
