### ISSUE TITLE
sr~ not working in pd 0.52

### ISSUE THREAD

**Issue by timothyschoen** [porres/pd-else#1181]
It seems that pd 0.52 no longer has the function sys_get_audio_params, which causes sr~.c to fail compilation.

**Comment by porres** [comment]
what version of ELSE are you trying to compile? I have fixed sr~ in the last version so it works with 0.52

please create separate tickets for each issue

**Comment by porres** [comment]
what do you suggest we do with rec?

**Comment by porres** [comment]
do I have to comment it all out?

**Comment by porres** [comment]
sys_get_audio_params doesn't get called, because in line 30 it's part of "static void audio_settings", which is called in "get_settings", which never gets called... it did get called in line 139, but it was commented out, as I showed you... https://github.com/porres/pd-else/blob/e9cd1d3795f95dc0bf104342fcfde3b75d291050/Classes/Source/sr~.c#L139

this is why I'm saying there's no problem, it's been fixed! And this is why I'm closing this :) if for some reason I need to comment it all out, I'll upload a commit soon that does this...

**Comment by porres** [comment]
>  A whole word search for "error(" will reveal them

I don't know how to do that :/

**Comment by porres** [comment]
already fixed muself

**Comment by porres** [comment]
though yeah, I don't know what to do with retrieve...

**Comment by porres** [comment]
would you help me find 'error' functions in https://github.com/porres/pd-cyclone?

**Comment by timothyschoen** [comment]
Yeah I'll check, but it seems to compile fine already for me!

**Comment by porres** [comment]
retrieve is based on cyclone/grab, so I already fixed that one... maybe there's more
