### ISSUE TITLE
Integer box

### ISSUE THREAD

**Issue by timothyschoen** [porres/pd-else#1294]
I have a fork of t_my_numbox lying around that works like an integer box: it converts any incoming number to an integer, while also only allowing typing/dragging integers. I think it's sometimes conceptually useful to work with integers, even when pd will convert it to a float anyway.

Let me know if you're interested in this, and if you're not, maybe we can put it into cyclone? 

You can close this issue if you want, I just wanted to know how you feel about this.

<img width="497" alt="Screenshot 2022-07-28 at 17 28 27" src="https://user-images.githubusercontent.com/44585538/181577209-ec69f098-dcea-4517-93ea-f020fed624b0.png">

**Comment by porres** [comment]
> I have a fork of t_my_numbox lying around that works like an integer box: it converts any incoming number to an integer, while also only allowing typing/dragging integers. 

typing/dragging integers in number boxes in Pd are also possible, of course. I mean, you only type and drag floats if you really want to, so there's nothing different about it right?

Seems like the only useful thing is that it automatically converts floats to integers on the input, so it only saves us including an [int] object before it, right?

> I think it's sometimes conceptually useful to work with integers, even when pd will convert it to a float anyway.

Well, honestly, I am failing to see how useful this is. Maybe cyclone would be a good place to include this if you really really want because it does have an integer box. I am really not much into adding anything new to Cyclone, just maintain it, but that's on me, people can still propose new things/objects, of course. I guess that what would be more interesting than an int box, though, is a compiled [number~] object. currently we have an abstraction that is not that great, of course. I don't want to remove it because it is useful in the documentation. I also hate the design of max's number, as usual. If we had a nice compiled number~ object for cyclone, I'd probably also steal it and change it to include in ELSE in a design that I think it's better. So, yeah, if you really want it, I'd really ask you to consider helps us working on a better number~ object :)

cheers

**Comment by timothyschoen** [comment]
Reading these reasons, I agree with you, it's not an amazing addition for ELSE. Just not very necessary. 

One reason behind it for me is that PlugData handles float precision based on the x-coordinate you're dragging at. This is great for entering floating-point numbers, but not for cases where you only want integers. I was hoping to get this object into either ELSE or cyclone, so I could add an integer object into PlugData while also keeping it compatible with Pd-vanilla (as long as ELSE and cyclone are installed). For cyclone, I guess that it's still a valid addition, maybe we could take that route then?

I'd love to help with a good number~ object too though! Is there any progress on this already, or should I start from scratch?

**Comment by porres** [comment]
> maybe we could take that route then?

yeah, let's go there.

> I'd love to help with a good number~ object too though! Is there any progress on this already, or should I start from scratch?

there's only the current [number~] abstraction

**Comment by timothyschoen** [comment]
https://user-images.githubusercontent.com/44585538/181663279-7167803e-a86d-4abf-a5ef-fece1b98a7a2.mov

[number~] demo, still a work-in-progress, but coming along nicely.

**Comment by porres** [comment]
by the way, if the vanilla knob doesn't get in soon (in next 0.53 version, hopefully to come out soon in a couple of months), I'm gonna go ahead and include it in ELSE temporarily. I needed help though cause I have troubles compiling and adapting the code as an external

**Comment by porres** [comment]
it's in here btw, https://github.com/Ant1r/pure-data/tree/feature/knb3

**Comment by timothyschoen** [comment]
Good idea, I'm also sorely missing a knob object! I might have time to help, but I'll finish the [number] and [number~] first.

One thing that's pretty cool is that all the regular IEM parameters work with the new [number~]. So you can already set color, auto init, label, snd/rcv and size. It also has a second outlet now, which outputs the values that are shown on screen. I still have to add a parameter for the refresh rate, but after that it should be nearly good to go!

<img width="713" alt="Screenshot 2022-07-29 at 04 39 35" src="https://user-images.githubusercontent.com/44585538/181671451-5dc2b4cc-0252-4698-b20d-24b26fa7bc3e.png">

**Comment by timothyschoen** [comment]
[number~] is almost ready, do you want me to send a PR to ELSE or cyclone?

**Comment by timothyschoen** [comment]
<img width="1111" alt="Screenshot 2022-07-29 at 16 46 22" src="https://user-images.githubusercontent.com/44585538/181785270-e9683e96-ebd4-4b8d-b491-ee248a5dd742.png">

This is the interface I settled on, but feel free to make changes.

**Comment by porres** [comment]
send it to cyclone!

**Comment by porres** [comment]
can't wait, where is it? :)

**Comment by timothyschoen** [comment]
I forgot to implement the "ramp" feature, I'm working on that now
