### ISSUE TITLE
numbox~

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1308]
- hitting enter doesn't work in the properties dialog
- we should revise the properties tcl/tk code and make lots of comments on it so I can begin to grasp and understand what this crazy thing is...
- in edit mode, I'd like to have a double arrow in the right edge to set the box width, maybe a corner bottom right diagonal arrow to also set font size.
- I would also like that we could set it to show or hide inlet/outlet and maybe supress the preceding tilde character
- calculating the width is not the best thing, it's a wild guess, but seems better than iemguis' nightmare

**Comment by timothyschoen** [comment]
The width for IEMGUI numbox is an absolute nightmare! I only very recently figured out how to get it right in PlugData...

Weird that hitting enter doesn't work for you, I have a slightly outdated version where it does work. At least it works for the height and width property, which are the only ones where it really matters.

Undo mystery: no idea... Very strange.

I can comment some more on the Tcl/Tk code, although I'm also not sure why we're doing certain things, I just made sure it does the same things as the original code.

Up and down arrows can be done, I've implemented it on [numbox] already. I'll send a pull request for arrow keys in [numbox~] soon.

I guess sys_queuegui are used to update the GUI asynchronously. I think we can safely replace by just calling the function it passes in. For the repainting of the signal I actually had to do this, because otherwise there would be too much delay.

**Comment by porres** [comment]
> Weird that hitting enter doesn't work for you, I have a slightly outdated version where it does work.

it is now working for some reason...

**Comment by porres** [comment]
> I'll send a pull request for arrow keys in [numbox~] soon.

Thanks, I worked on top of it and improved it. We gotta do this for iemguis and at least number atom box ;)

I wonder if there is a way to listen for events without using the general 'list' method, it would be more elegant. What do you say?

**Comment by porres** [comment]
> I guess sys_queuegui are used to update the GUI asynchronously. 

But why does it need to be updated asynchronously?

> I think we can safely replace by just calling the function it passes in. 

Me too, I will try and do that.

**Comment by porres** [comment]
> I can comment some more on the Tcl/Tk code, although I'm also not sure why we're doing certain things, I just made sure it does the same things as the original code.

Please have a look at oscope~ as well, which has a separate file and also has some comments. By the way, I wanted to remove "alternate drawing" from oscope~ and failed mierably in doing so :/ perhaps you can help me with that too. Maybe checking out oscope~ will help clear things out for you as well.

I really really really need help finding my way around tcl/tk and maybe @brbrofsvl can help as he wrote the oscope~ dialog in a hospital bed recovering from a spider byte and seem to have mastered it quite well... maybe he got super powers like spider man.

Matt, I know it's a lot of work, but maybe it's summer and you can help us by writting more comments on how this crazy dialog code works. It could be for cyclone/scope~! It's still on my to do list by the way to provide a decent dialog for cyclone/comment (and else/note). Tim is willing to help with that too. It's about the last thing needed for cyclone so we can say we finished it and completed it :)

**Comment by porres** [comment]
> I wonder if there is a way to listen for events without using the general 'list' method, it would be more elegant. What do you say?

Weirdly enough, our new list method for key presses ruins the float input method. This does not make sense and I'm now questioning my sanity or the laws of physics and the universe itself.

And instead of capturing from a float a one float element list that is a float, I get a zero length list (ac = 0).

**Comment by porres** [comment]
instead of "class_addlist" we had "class_addfloat" for the list method... :)

**Comment by timothyschoen** [comment]
oof my bad

**Comment by porres** [comment]
fix this and other things, revised the code some more, remore "queue gui" stuff and added a 'set' method that saves internal state (this should be added to properties as well).

**Comment by porres** [comment]
> it is now working for some reason...

sometimes it does not work... it's weird

**Comment by porres** [comment]
we should also bind "keyname" only when the box is activated, this is done in [note]

**Comment by brbrofsvl** [comment]
It was a dog bite. I still have the scars from both the bite and the dialog.

I mostly just copied code from the main GUI dialogs, but since it has to be done in c for externals, we run the sys_gui() function for every single line of tcl/tk code, using \n for newlines.

Since tcl/tk is an opaque garbage language, I've mostly flushed it all from my brain. But if you have specific questions maybe we can work on it. Half the time I felt like I was doing "this has to go here because it seems like it has to go here based on what happens in the other dialogs."

Most of the commands, though, are easy to find online. The hard stuff if I remember correctly is the weird $ syntax for variables.

**Comment by porres** [comment]
@brbrofsvl, I guess the best way to help is if you can make comments in the dialog.c file describing what is does and what you remember that makes sense. I am impressed how you were also able to draw the scope in the properties. I'd love if we could do something similar for else/note and cyclone/comment.

**Comment by porres** [comment]
I would also like to have an exponential curve for numbox~/numbox like in https://github.com/pure-data/pure-data/issues/1647

**Comment by brbrofsvl** [comment]
@porres Yeah, the scope drawing was the simple part – it's all the button stuff that's a pain.

I can give it a go with the comments.

**Comment by porres** [comment]
@brbrofsvl I couldn't even remove "alternate drawing" from my "oscope~" version. I couldn't believe how miserably I failed on that. I'd love some help to be able to do that and understando what needs to be done.

**Comment by porres** [comment]
> we should also bind "keyname" only when the box is activated, this is done in [note]

just did it

**Comment by porres** [comment]
@timothyschoen I added a new parameter which is an initialization value, but this doesn't work like in iemguis. In iemguis you have savestating, in mine you have a value you set and it loads it when you open the patch. By default, it is 0.

Check it out, all that is left is also adding this to the properties window.

**Comment by timothyschoen** [comment]
I can make some time for that tomorrow!

**Comment by timothyschoen** [comment]
<img width="456" alt="Screenshot 2022-08-18 at 12 40 38" src="https://user-images.githubusercontent.com/44585538/185376145-0cc45683-82c1-4c81-ae88-b5aa94b90d77.png">

Another bug: if you click the close button in the titlebar, this happens. I'll see if I can fix that

**Comment by porres** [comment]
thanks, looks good! Done for rc3 at least ;)

**Comment by porres** [comment]
rebooting this with a new list of things
