### ISSUE TITLE
revise and fix other random generating objects

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1311]
@brbrofsvl, I'm using Pd's method, which I don't know what it is, maybe Linear Congruential Generator?

You used a different one for else/pinknoise~, what do you have to say about this?

I'm considering also changing the method for my objects

**Comment by porres** [comment]
random.h is used in:
- brown~
- clipnoise~
- gray~
- pinknoise~
- pluck~

we got many other "noise" objects and random number generators (list coming soon)

**Comment by porres** [comment]
seed in objects like brown~ should also have an initial seed based on system time. Float input is not working in [brown~] to set seed, btw! A "seed" message might be better, what about a flag/argument?

**Comment by porres** [comment]
all functions in random.h/c don't seem to be in use.

**Comment by porres** [comment]
> seed in objects like brown~ should also have an initial seed based on system time. Float input is not working in [brown~] to set seed, btw! A "seed" message might be better, what about a flag/argument?

same with pinknoise~

**Comment by porres** [comment]
fixed seed issue with brown~ and pinknoise~!

I checked but couldn't understand how the random function works, neither how the objects differ

@brbrofsvl, please help me figure it out :)

**Comment by porres** [comment]
rename pinknoise~ to pink~?

**Comment by brbrofsvl** [comment]
@porres when you say you can't figure out how the objects differ, do you mean SuperCollider's pseudo RNG and Pd's, or do you mean pink~ vs brown~?

**Comment by porres** [comment]
pink~ vs brown~ but it's not important

I now added white~, the object I was reluctant to add, but now I think it's worth it and I see advantages over [noise~] besides the quality of the random generator, which is the ability to load different seeds based on system time. I'm now making a PR so this is also true for vanilla...

Anyway, I was hoping to better understand this random number generator on its own before how the objects work, but I need to make detailed questions. It would be good for me to know a bit about the implementation details so I could write about it in my tutorial, not only about the technique used for the PRNG, but also how brown~ and pink~ are made.

Oh, and I am also considering including other noise objects I have here from you, like the distributed noise one.

**Comment by brbrofsvl** [comment]
brown~ is a bounded random walk, with max step == 0.125 (the max step size could be settable with a message if you wanted). If it tries to step outside the bounds -1.0 to 1.0, it just gets reflected back in (if it tries to step to 1.02, the output value will be 0.98).

pink~ uses the Voss-McCartney algorithm for generating pink noise, where you mix a bunch of sample&hold noises with periodicities related by octaves. Each octave of noise you add adds another 3dB to its octave since it's uncorrelated with the rest of the noise. That way on average you'll end up with a noise with pink color. Been a while since I looked, but I believe the SC implementation staggers the update of each noise for minimal load, so that you only need two RNGs.

**Comment by porres** [comment]
is brown some sort of random walk?

**Comment by porres** [comment]
what do you think of a parameter that sets the step value of brown?

**Comment by brbrofsvl** [comment]
brown~ is a bounded random walk, with max step == 0.125 (the max step size could be settable with a message if you wanted). If it tries to step outside the bounds -1.0 to 1.0, it just gets reflected back in (if it tries to step to 1.02, the output value will be 0.98).

Setting the max step size can be very useful, in the range 0-1. Anything higher than 0.5 will likely begin to approach white.

**Comment by porres** [comment]
@brbrofsvl  this has been great for adding more information to the help files and my tutorial, I also included a way to implement [brown~] in Vanilla.

Now, what about the "quality" of the pseudo random number generator? What kind of algorithm is it? I know Miller says his is "completely homebrew, non standard and untested"... so it seems it's no standard type. How about ours? (which is SuperCollider's)?

Also, it'd be great if you could give me more detailed information on [gray~] and [perlin~] so I can properly explain them. These don't seem to be standardly used in music, right? Unlike pink~ / brown~ / white~

What do we have to say about the quality of their sound?

**Comment by porres** [comment]
> @brbrofsvl, I'm using Pd's method, which I don't know what it is, maybe Linear Congruential Generator?

I'm using Pd's method for many of my random number generator and I'm now changing to the one we are using... and I was asking if maybe pd's one is some sort of "Linear Congruential Generator", a known type of PRNG algorithm.

**Comment by brbrofsvl** [comment]
PD's is an LCG but not one of the standard ones. I'm not at a computer so I don't remember what SC's is. I'll look when I get home.

More on the others soon

**Comment by brbrofsvl** [comment]
SuperCollider's is a Tausworthe generator
https://github.com/supercollider/supercollider/blob/18c4aad363c49f29e866f884f5ac5bd35969d828/include/plugin_interface/SC_RGen.h

There's not a lot of documentation on it but I might be able to find the paper he mentions. 

>Also, it'd be great if you could give me more detailed information on [gray~] and [perlin~] so I can properly explain them.

Sure. gray~ is a Gray code noise. A gray code is a list of numbers where you change one bit at a time. They're useful for all sorts of things (I have used them to slowly morph parameters in a composition, for instance). One of the original uses was for making mechanical dials, because changing only one thing is much less likely to fail than if you change lots of them. Anyway, you can flip a random bit in an int and then convert that to float. Here's the code from SuperCollider:

 LOOP1(inNumSamples, counter ^= 1L << (trand(s1, s2, s3) & 31); ZXP(out) = counter * 4.65661287308e-10f;);

trand(s1, s2, s3) & 31 is a random integer between 0 and 31, inclusive. So we're shifting to the left a random number of places. Then to flip you just bitwise XOR using the ^ operator. Very efficient and cool.

I know nothing about its spectrum, but SC says it emphasizes low frequencies.

perlin noise is a 1-dimensional perlin noise generator. Perlin noise is usually used in multiple dimensions to get interesting landscape kinds of pictures. In 1D, the idea is basically that at periodic intervals you choose a new slope for the tangent line at a zero crossing, and then use a fancy interpolation algorithm called "smoothstep" to join them.

Visual here:
https://jameshfisher.com/2017/10/15/1d-perlin-noise/

smoothstep:
https://en.wikipedia.org/wiki/Smoothstep

**Comment by porres** [comment]
@brbrofsvl  - it seems I have from you some low frequency noise abstractions, two of which are [noise4~] and [noise4sm~]. Do you confirm and remember these? See attachment. I wanna see if I can code this as a compiled object. Quick question, what is "4" and "4sm" for? I wanna include this as extra interpolation options for my [lfnoise~] object

**Comment by porres** [comment]
the attachment: [noise-samphold-examples.zip](https://github.com/porres/pd-else/files/9333593/noise-samphold-examples.zip)

**Comment by porres** [comment]
And this is your noise distribution object, that I'm also consiering including 
[noise-dist_.zip](https://github.com/porres/pd-else/files/9333596/noise-dist_.zip)

**Comment by porres** [comment]
> what is "4" and "4sm" for?

I might choose only one of these two, it seems "4sm" is quite smoother and makes more of a difference for lower frequencies.

While we're at it, this is kind of like the same thing for [perlin~], right? It just chooses a random value and does some fancy interpolation to reach it, am I correct?

**Comment by brbrofsvl** [comment]
The 4 is for the cubic interpolation. Plain 4 uses the same Lagrange interpolator as tabread4~. 4sm uses an Hermite one which matches first derivatives in order to make transitions between segments smooth. The difference with perlin is that instead of picking a random point periodically, it picks a random slope periodically, and you're guaranteed a zero crossing at each period.

**Comment by brbrofsvl** [comment]
For the interpolating ones, I love having the ability to put in whatever noise source you want, so there can be more general samphold objects with interpolation for any signal

**Comment by porres** [comment]
>  I love having the ability to put in whatever noise source you want

I have another object that is more flexible and suited for that, called "downsample~", where you can have any input. My idea was to also include these interpolation options in [downsample~] and have [lfnoise~] basically the same thing but for white noise only. With this, I don't need to add any new object. I also have [stepnoise~] and [rampnoise~] just if you want random steps or ramps from white noise (I only use these anyway). If you want more options, you can use [lfnoise~], if you want other noises, you use [downsample~]. The probability distribution noise is something cool to add into all this.

Now, hermite is also used in cyclone, right? I forgot the object, we got like 7 interpolation options... maybe I can use that for the compiled code. I also need to add interpolation options for my table reading objects in else.

> The difference with perlin is that instead of picking a random point periodically, it picks a random slope periodically, and you're guaranteed a zero crossing at each period.

thanks for clarifying, really useful :)

**Comment by brbrofsvl** [comment]
The cyclone object is wave~. There are a number of different Hermite interpolators. The wave~ one is a little different than the one I used in the noise4sm~ – the latter one uses standard numeric differentiation formulas for matching slopes at breakpoints.

A quick note that the Lagrange interpolator is actually more correct between points, and if you are interpolating over a very smooth function like a sine wave, it will have less distortion than the hermite one. Another thing is that while the lagrange one does not have continuous first derivative (no jumps in slope – smooth breakpoints), it does have continuous second derivative (no jumps in concavity). The hermite one has continuous first derivative but not second derivative, so you can see weird changes in concavity with that one.

**Comment by brbrofsvl** [comment]
Also, if you do end up using Chuck Henry's Gaussian noise technique in brown~, be sure to read the cos component from a table so you're not running the cos() function every sample.

Actually, if the Gaussian noise is a separate object, you could share the routine between them. Or, you could have a "browning" filter that takes a signal of the user's choice and uses it as a source for the brownian steps. I have some ideas for how to do this but I can't implement them until about september since I have to get everything in order for the semester.
