### ISSUE TITLE
why is [fbdelay~] fucked up?

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1446]

**Comment by esaruoho** [comment]
ok something is terribly wrong with `fbdelay~-help.pd` - if i set the `[else/out~]` to a regular volume and then change the Delay time, it immediately outputs extremely super ultra extra loud sounds. talking ear-splitting deafness inducing sounds. i hope this is the only one.

since the object itself cannot be opened by right-click -> open, i have no way of knowing why the `float/signal - delay time (im ms)` is so utterly broken.

**Comment by porres** [comment]
answer: because of the newly added spline interpolation

**Comment by porres** [comment]
the lagrange also fucks it up if called from buffer.c
