### ISSUE TITLE
[sfont~] could'nt be created under Manjaro Linux

### ISSUE THREAD

**Issue by joe-rouen** [porres/pd-else#1496]
Hello,

There is an issue with [sfont~] under Manjaro 22 (Arch Linux base).
In Pure Data Vanilla 0.53.1 console:
_/home/joe/Pure-Data/externals/else/sfont~.l_amd64: libpcre.so.3: cannot open shared object file: No such file or directory
else/sfont~ -g 0.3
... couldn't create_

Other Else objects like [keyboard], [pitch2note] and [out~] are okay.

Manjaro system is up to date: sudo pacman -Syu

After further investigations, libpcre.so.3 is not available on Manjaro Linux but only:
libpcre.so, libpcre.so.1, libpcre.so.1.2.13 in both /lib and /usr/lib32 folders.

The 4 current libraries available in the Manjaro repositories are installed:
- lib32-pcre 8.45-3 (multilib)
- lib32-pcre2 10.41-1 (multilib)
- pcre 8.45-3 (core)
- pcre2 10.42-2 (core)

The Manjaro/Arch community seems to say:
_"libpcre.so.3 is not missing. It's a Debian version of libpcre.so.0. Nothing on Arch should depend on it!"_

Please note that Purr Data [fluid~] is working okay under Manjaro 22.

What can be done by an average user?
Thank you.

**Comment by porres** [comment]
@reduzent could you help?

**Comment by porres** [comment]
@agraef maybe you can help too

**Comment by agraef** [comment]
Hi Joseph,

That's the version from Deken, right? Yeah, same issue over here. Presumably this was built on some Ubuntu system with old libraries that don't match up with Manjaro.

Here's a version I built for vanilla on Manjaro from the latest git source just a few minutes ago. This one actually works, and it includes a working sfont~. Of course, you need to have the fluidsynth package installed, but if you have purr-data on that system then you should already have all the needed dependencies.

[else.zip](https://github.com/porres/pd-else/files/10714481/else.zip)

**Important:** Make sure that you completely get rid of the *entire*  else directory from Deken, do *not* just install my version over it, that won't work. After deleting the old version, just drop the contents of else.zip from above in its place (or anywhere else where you want it to go).

I should maybe upload a PKGBUILD for ELSE to the AUR some time, but I'm just too busy with too many things.

Good luck!
Albert

**Comment by agraef** [comment]
Ok, @porres, now that I've done something for you, you can do something in return: **Go fix #1477 immediately!** For anyone else who happens to read this: ELSE currently bundles an outdated and, even worse, broken pd-lua version. Don't use it. Until Alexandre fixes this, use the upstream package at https://github.com/agraef/pd-lua instead.

**Comment by joe-rouen** [comment]
Hello Albert,

Yes, it was the Else 1.0-0 rc-6 one from Deken.

Great. Your Else 1.0-0 rc-7 unreleased Built worked straightaway like a charm!
[else/sfont~] is now available under Manjaro Linux.

Thank you very much for your contribution and very quick fix.
Joseph

**Comment by agraef** [comment]
Glad that it works for you. Happy ELSE'ing. :) It's a great library, I just wished that Alexandre was more responsive to urgent bug reports. ;-)

BTW, I have a preview of purr-data including ELSE over at https://github.com/agraef/purr-data/tree/pd-else (look for the 2.19.2+ELSE pre-release), in case you want to give that a go. (Note, however, that none of the gui features have been ported at this time, so keyboard et al won't work yet.)

**Comment by agraef** [comment]
BTW, once Alexandre has merged #1497, you can easily build and install sfont~ along with else yourself, using a single make command in the toplevel dir, something like:

~~~
make install sfont-install pdincludepath=$(pwd)/../pure-data objectsdir=$(pwd)/else-build
~~~

This assumes that you have the vanilla sources in ../pure-data, and will install the entire shebang into ./else-build, from where you can copy it to whatever location you want. (In fact, that's exactly how I did it in order to create that zip archive.) Note that the Pd *source* is needed for some extra include files which don't get normally installed and hence are not in the official pd package from the Arch community repository.

But you don't need to do a staged install, you can also just install ELSE directly into vanilla's /usr/lib/pd/extra directory:

~~~
sudo make install sfont-install pdincludepath=$(pwd)/../pure-data objectsdir=/usr/lib/pd/extra
~~~

That's where an official Arch package would install it, if we had one. If you omit the objectsdir definition, installation will go into /usr/local/lib/pd-externals which also works because vanilla has this directory on its built-in search path on Linux.

**Comment by reduzent** [comment]
> I just wished that Alexandre was more responsive to urgent bug reports. ;-)

The issue 6 hours old. What is your expectation?

**Comment by reduzent** [comment]
The version from Deken ships most depencencies, but libpcre is excluded, specifically it is excluded in the `exclude_path` variable in the script `localdeps.linux.sh`. You could just remove it from the exclusion list, so that the sfont~ externals uses its local version of libpcre.

**Comment by agraef** [comment]
@reduzent, I was referring to another ticket, not this one.

**Comment by joe-rouen** [comment]
> The version from Deken ships most depencencies, but libpcre is excluded, specifically it is excluded in the `exclude_path` variable in the script `localdeps.linux.sh`. You could just remove it from the exclusion list, so that the sfont~ externals uses its local version of libpcre.

Well, I'm unable to find `localdeps.linux.sh` on my whole Manjaro disk ("/"), so I can't modify it.

For the time being, I'm staying with Albert's build solution until Alexandre will be able to release a modified Else/Deken version for Manjaro/Arch or a more general one for GNU/Linux.

Thank you.

**Comment by agraef** [comment]
Joseph, the script that @reduzent mentioned is in the source code, and he already submitted a PR to have that fixed, so that hopefully a future Deken release of ELSE will include all the libraries required to have the external work on Arch/Manjaro.

For the time being, just continue to use what I posted here. When I find the time, I can also do an Arch PKGBUILD, and submit that to David Runge who maintains all the multimedia stuff in the official Arch community repositories.

**Comment by agraef** [comment]
There you go: https://aur.archlinux.org/packages/pd-else-git

You can install this with `yay -S pd-else-git`. yay will pull the latest pd-else and pure-data git sources, build the package from that, and finally installs the package. pd-else including sfont~ goes into /usr/lib/pd/extra/else and the README.md into /usr/share/doc/pd-else-git, just like an official package would do.

Once Alex releases the next rc, I can turn this into a stable (rather than git) package and submit it to David so that it goes into the official Arch repositories.

**Comment by agraef** [comment]
So basically @porres got two fixes for this bug now.

**Comment by joe-rouen** [comment]
Hello Albert,
Thank you for your latest developer explanations.
It's now much clearer for me an average user. ;)

**Comment by agraef** [comment]
Joseph, no problem, as you can tell I struggled with the same issues when I first tried ELSE on Manjaro. :)

At least we have that PKGBUILD now to remind us how to build and install pd-else if the need arises. It's not that complicated really, and the source does compile and install cleanly thanks to pd-lib-builder. Building a package for Deken is more involved, as it needs to work on a large variety of different Linux and non-Linux systems.

**Comment by agraef** [comment]
Turns out that the last (rc6) release builds just fine with my build script as well, so here is the stable version of the package: https://aur.archlinux.org/packages/pd-else

@dvzrv: Maybe you could take this under your wings? pd-else is an almost all-encompassing, curated set of externals from various sources. A modern take on pd-cyclone, if you will, or "all the good parts" of pd-extended brought into the 2020s and rolled into a single library. It has some very nice gui objects for Pd as well, and serves as the backbone of plugdata's library. Yes, it's still a release candidate right now, but it's already quite mature and loved by many in the Pd community, so IMHO a spot in the official Arch repos would be well-deserved. At least when 1.0 proper comes out, which AFAICT is to be released later this year, but maybe you could kick it off with rc6 right now? Thanks for considering, Albert

**Comment by porres** [comment]
>  I was referring to another ticket, not this one.

it's a week old issue I said I'd get to before plugdata ships the new version in a week and before I make a new ELSE release at the same time :)

I feel I'm more active than I should most of the time. BTW, we have summer here and I'm also trying to enjoy a beach vacation and had a new Cyclone release in my priority list.  I thought I'd send a picture of me wearing a speedo taking a sun bath, but I'm sparing you people

**Comment by joe-rouen** [comment]
> it's a week old issue I said I'd get to before plugdata ships the new version in a week and before I make a new ELSE release at the same time :)
> 
> I feel I'm more active than I should most of the time. BTW, we have summer here and I'm also trying to enjoy a beach vacation and had a new Cyclone release in my priority list. I thought I'd send a picture of me wearing a speedo taking a sun bath, but I'm sparing you people

Alexandre you are, thousand times right!
Enjoy your holidays, look around for nice girls, surf on the Atlantic waves and back to the beach take some time to drink few Caïpirinhas! ;)
And of course forget for a while (not too long) both Else and Cyclone. :)
Here in Europe it's unfortunately the Winter season. :(

**Comment by porres** [comment]
don't forget brazilian carnival season is coming, which means I guess I won't be able to make the updates I wanted for cyclone 0.7 :( both will be updated this week anyway, and yes, I have a summer love story already to share  :)

**Comment by agraef** [comment]
> I thought I'd send a picture of me wearing a speedo taking a sun bath, but I'm sparing you people

Picture, or it didn't happen. :rofl:

**Comment by agraef** [comment]
BTW, @porres, the latest on master seems to be broken, here is what I get:

~~~
Classes/Source/else.c: In function ‘else_obj_version’:
Classes/Source/else.c:33:2: error: invalid preprocessing directive #elseif; did you mean #else?
   33 | #elseif PD_PLUGDATA_VERSION
      |  ^~~~~~
      |  else
In file included from Classes/Source/else.c:3:
Classes/Source/else.c:34:28: error: ‘PD_PLUGDATA_VERSION’ undeclared (first use in this function); did you mean ‘PD_BUGFIX_VERSION’?
   34 |     SETSYMBOL(at+1, gensym(PD_PLUGDATA_VERSION));
      |                            ^~~~~~~~~~~~~~~~~~~
~~~

**Comment by agraef** [comment]
You probably meant to write something like `#else if defined(PD_PLUGDATA_VERSION)`.

Github CI would have caught this immediately, maybe something else for your TODO list. :)

**Comment by agraef** [comment]
More like `#elif defined(PD_PLUGDATA_VERSION)` probably.

**Comment by agraef** [comment]
@porres: Even worse, you did the cardinal sin, 14-Trigger-LFO:LFNoise isn't a legal Windows path name since the days of DOS. ;-) No seriously, this means your source can't even be checked out on Windows any more, much less be compiled.

I fixed this in https://github.com/porres/pd-else/pull/1502, hopefully you won't let that sit there for another week while enjoying the beach. :))

**Comment by porres** [comment]
you didn't give me a PR for the other one, I took many of your PRs at the beach with my phone :)
