### ISSUE TITLE
free.rev~ does not accept messages for setting

### ISSUE THREAD

**Issue by esaruoho** [porres/pd-else#1566]
i used these to send to else/free.rev~
<img width="216" alt="Screenshot 2023-03-13 at 23 44 37" src="https://user-images.githubusercontent.com/4966687/224839089-9fd3533e-acdf-4810-b02a-f66b584da08e.png">

and they had no effect. in fact, i get the following errors to console:
<img width="243" alt="Screenshot 2023-03-13 at 23 45 17" src="https://user-images.githubusercontent.com/4966687/224839202-74583889-6b39-4ea6-99fa-52d654d62485.png">

the only way i can seem to set the free.rev~ parameters is to use the `[pd set]` 
<img width="489" alt="Screenshot 2023-03-13 at 23 45 46" src="https://user-images.githubusercontent.com/4966687/224839282-e392f31f-37b6-45e9-9e10-e85cb065d14a.png">

but the problem with this is that the minute i update Else from deken, the settings will get lost.

what should i do?

**Comment by porres** [comment]
I'm gonna close this because this is not a real issue, you just do not seem to have the latest ELSE from deken or you're using a very very old Pd version...

btw, you should always provide basic information about your setup, like Pd version, library version, OS and stuff.

your screeshot shows quite clearly that it should work, here's a broader view of the patch.

![Screen Shot 2023-03-13 at 15 58 38](https://user-images.githubusercontent.com/5360142/224856027-365d3956-6e93-4676-887c-383561cbded2.png)

we can keep troubleshooting even though this issue is closed

**Comment by porres** [comment]
I'm gonna close this because this is not a real issue, you just do not seem to have the latest ELSE from deken or you're using a very very old Pd version...

btw, you should always provide basic information about your setup, like Pd version, library version, OS and stuff.

your screeshot shows quite clearly that it should work, here's a broader view of the patch.

![Screen Shot 2023-03-13 at 20 42 14](https://user-images.githubusercontent.com/5360142/224856114-e20f8432-c8a2-4040-9fb1-d17436f5582a.png)

we can keep trouble shooting even though this issue is closed
