### ISSUE TITLE
sfz~ creation error, doesn't link 'elsefile'

### ISSUE THREAD

**Issue by porres** [porres/pd-else#1780]
For oher objects I'm using pd-lib-builder, which makes it easey. Like with sfont~, I do something like this

file := ../../../shared/elsefile.c 
sfont~.class.sources := sfont~.c $(file)

and it works. If I don't link this way I get the same kind of error, where it only creates if another object that uses elsefile and is built correctly loads first. 

the error I get is 

/Users/porres/Documents/Pd/externals/else/sfz~.pd_darwin:dlopen(/Users/porres/Documents/Pd/externals/else/sfz~.pd_darwin, 10): Symbol not found: _elsefile_free
  Referenced from: /Users/porres/Documents/Pd/externals/else/sfz~.pd_darwin
  Expected in: flat namespace
 in /Users/porres/Documents/Pd/externals/else/sfz~.pd_darwin

![Screen Shot 2023-08-22 at 04 11 50](https://github.com/porres/pd-else/assets/5360142/c6049afe-f145-421d-aa16-f8be76d8f7b1)

**Comment by porres** [comment]
@alcomposer

**Comment by porres** [comment]
@Lucarda

**Comment by Lucarda** [comment]
I'm about for a sleep cycle.

the thing is https://github.com/porres/pd-else/issues/1683#issuecomment-1628032730 that `elsefile.c` must also be compiled with `sfz~.c` like you do with pd-lib-builder. but i don't know how to tell that to `cmake`. that's why my ugly idea to add all `elsefile.c` code into file `sfz~.c`.

**Comment by porres** [comment]
yay, fixed
