### ISSUE TITLE
error messages when making objects or opening help file

### ISSUE THREAD

**Issue by H-MLim** [porres/pd-else#1887]
![image](https://github.com/porres/pd-else/assets/68152553/a984d2d4-1c70-4af0-a575-d9939785e05b)

those error messages are printed when I tried to make new objects or open help file of several objects (what I tested are `rand.u`, `out~`, `keyboard`, etc.) . what should I do? my pd and ELSE are most recent ones and I'm still using Win 11.

(btw afterwards, the objects were created and worked well in spite of these messages. meanwhile this didn't happen in plug data.)

**Comment by porres** [comment]
I don't know what to do... I need a patch that shows the behaviour, maybe a video

I have no idea what's going on. Can you also confirm the versions instead of "recent onde"?

so, it says it can't create and then it magically creates and works?

sorry, I don't know what to make of this bug report, maybe @Lucarda can shed some light as he's the Windows Wizard

**Comment by H-MLim** [comment]
woops...sorry. I thought I was in ver.0.54 since I downloaded and installed the update program. but it seems the update wasn't installed well and it was still 0.53-2. now this works well in 0.54. sorry for confusing and will close this issue.
