### ISSUE TITLE
which README?

### ISSUE THREAD

**Issue by umlaeute** [porres/pd-else#490]
the repository contains 3 different README files:
- README.pdf
- README.md
- Help-files/README.pdf

are they redundant?
- the the PDF in `Help-files` seem to have a list of objects (as opposed to the other two files in the root-directory)

- can `README.pdf` be generated from `README.md` (thus making the pdf superfluous)?
- could `Help-files/README.pdf` be generated as well?

**Comment by porres** [comment]
the one in  Help-files/README.pdf is an accident just got rid of it https://github.com/porres/pd-else/commit/2adb4cfeb8b7320f108f8400d8bca03b8b3cd413

I'm generating README.pdf from README.md and I'm using the PDF to go into the generated else folder.

> the the PDF in Help-files seem to have a list of objects (as opposed to the other two files in the root-directory)

it was the same information, but it came out as a list with different lines, instead of the others who group the objects differently. I generated that PDF in a different way, by accident, and saved it by accident there. I use macdown to generate a PDF.

> can README.pdf be generated from README.md (thus making the pdf superfluous)?

sorry, I don't understand. Yeah I generated from the md file, but what's the problem?

**Comment by umlaeute** [comment]
> the one in Help-files/README.pdf is an accident just got rid of it [2adb4cf](https://github.com/porres/pd-else/commit/2adb4cfeb8b7320f108f8400d8bca03b8b3cd413)

:+1:

> 
> I'm generating README.pdf from README.md and I'm using the PDF to go into the generated else folder.

cool.

> > can README.pdf be generated from README.md (thus making the pdf superfluous)?
> 
> sorry, I don't understand. Yeah I generated from the md file, but what's the problem?

no problem.
i'm currently evaluating pd-else for Debian packaging, and for this i need the sources of all binary blobs (like PDFs). obviously the README.md is just that.

"the pdf [being] superfluous" is just that: the PDF is not strictly needed in the source code repository (as the source code is the markdown file, and you can generate the pdf from that).

**Comment by porres** [comment]
cool, guess we can close this then
