### ISSUE TITLE
dinamically allocate t_atom size (function / note) and t_float size (median~)

### ISSUE THREAD

**Issue by porres** [porres/pd-else#881]
We (me and @emviveros ) are getting errors when trying to compile ELSE with camomille - see https://github.com/emviveros/Camomile-ELSE/issues/1

it complains when we initialize atoms like this in:
- https://github.com/porres/pd-else/blob/master/Classes/Source/function.c#L403
- https://github.com/porres/pd-else/blob/master/Classes/Source/note.c#L804

similarly, initializing t_float here gives the same error:
- https://github.com/porres/pd-else/blob/master/Classes/Source/median~.c#L52

@pierreguillot says the error is described here https://stackoverflow.com/questions/9881777/why-do-i-get-cannot-allocate-an-array-of-constant-size-0 in this comment from camomille's repository https://github.com/pierreguillot/Camomile/issues/138#issuecomment-738111255

I'm quoting from the above link this citation "_You cannot allocate an array of unknown size with automatic storage duration in C++. If you want a variable sized array then you need to dynamically allocate it (or, better yet; just use a vector)._"

The problem is that me and esteban do not know how to do this and we're looking for help.

thanks.

**Comment by giuliomoro** [comment]
I thought Pd was compiled  with `-std=c99`, which would support variable length arrays (VLA) ... but then clearly Visual Studio does what it wants, it thinks it's a C++ (and not C) file and C++ does not support VLA ...

Anyhow, you should probably use `alloca()` instead, that's used widely in the Pd codebase.
e.g.:
```
    t_atom at[ac];
```
becomes
```
t_atom* at = alloca(ac * sizeof(t_atom);
```

The rest of the code should not require any changes.

**Comment by porres** [comment]
I'm attempting to fix with 'malloc', let's see... if it works I'll also try alloca!

**Comment by giuliomoro** [comment]
`alloca` is the drop-in replacement for VLA because it allocates on the stack. `malloc()` does something different because it allocates on the heap and is not real-time safe (it could cause a page fault and. Unless you need a lot of memory, or memory that needs to survive outside the current scope (end of the function in this case), `alloca()` is the way to go. Also I think in Pd you should use `getbytes()` instead of `malloc()` directly (though I am not 100% sure about this). This basically calls `calloc()` (which is like `malloc()` but iniitalises memory to 0) and keeps track of the allocated memory.

**Comment by porres** [comment]
hmmm, like this right? https://github.com/porres/pd-else/blob/56dcf6691ff8fd60d9c9486591a5147f683782a2/Classes/Source/merge.c#L34

**Comment by porres** [comment]
@giuliomoro : my fear with alloca is that I've seen somewhere that it may not be available in some compiling situation

so I wonder if getbytes & freebytes will effectively be the same thing wihtout any disadvantage, with the advantage of not needing to call any other header dependency

**Comment by porres** [comment]
> so I wonder if getbytes & freebytes will effectively be the same thing wihtout any disadvantage, with the advantage of not needing to call any other header dependency

using getbytes & freebytes for function/note here now https://github.com/porres/pd-else/commit/8d086a97dca1ea98916aad8b8d50c6010d46fdfd

seems like there will be no issue as the else/merge object uses this and presented no error. So I'm about to close this. Just want a confirmation from @giuliomoro that this is totally worry free!

**Comment by pierreguillot** [comment]
With Pd, I suggest you use getbytes (or malloc). You should read the notes about alloca https://man7.org/linux/man-pages/man3/alloca.3.html.

The alloca() function is machine- and compiler-dependent.  For certain applications, its use can improve efficiency compared to the use of malloc(3) plus free(3).  In certain cases, it can also simplify memory deallocation in applications that use longjmp(3) or siglongjmp(3). **Otherwise, its use is discouraged.**

**Comment by porres** [comment]
compilation successful :)
